### ISSUE TITLE
Storyboard names

### ISSUE THREAD

**Issue by Ashton-W** [paulsamuels/SBConstants#16]
I don't fully understand the template format yet, so I don't know if this only requires a template update.

Could we include constants for the storyboard name?
As used in `+ (UIStoryboard *)storyboardWithName:(NSString *)name bundle:(NSBundle *)storyboardBundleOrNil`

**Comment by orta** [comment]
You could run the ruby gem per storyboard and name the file differently?

**Comment by Ashton-W** [comment]
I don't follow @orta?  How would that create constants with the name of the `*.storyboard`?

**Comment by orta** [comment]
```
storyboard_ids:
	bundle exec sbconstants Kiosk/Storyboards/MainStoryboardIdentifiers.swift --source-dir Kiosk/Storyboards/Main --swift
	bundle exec sbconstants Kiosk/Storyboards/OtherStoryboardIdentifiers.swift --source-dir Kiosk/Storyboards/Other --swift

```

**Comment by Ashton-W** [comment]
I'm using Objective-C if that makes a difference

**Comment by Ashton-W** [comment]
@orta, maybe the Swift templates are different, but the ObjC template does not include the name of the storyboard

**Comment by orta** [comment]
Looks like it does to me in the README, I just used that as I had it to hand.

**Comment by orta** [comment]
Note, mine doesn't include the storyboard name either
