### ISSUE TITLE
Custom `objc_body.erb` template isn't used

### ISSUE THREAD

**Issue by Ashton-W** [paulsamuels/SBConstants#18]
The default template is always used for `objc_body`.

See: 
https://github.com/paulsamuels/SBConstants/commit/0edae9903462c840783dea2bf03553f7ff818030#diff-a7b70ae59847e3f939f89777f94834c8R36

**Comment by paulsamuels** [comment]
Good spot this was me being slightly narrow sighted and just fixing the initially raised issue without looking at other potential uses

**Comment by paulsamuels** [comment]
@Ashton-W are you happy this issue is resolved (by your own work :+1:)

**Comment by Ashton-W** [comment]
Yes, it is working for my uses.

(we need some tests :+1:)

**Comment by paulsamuels** [comment]
Yes it's embarrassingly lacking on tests - tbh didn't really expect anyone else to ever use the tool
