### ISSUE TITLE
What are queries?

### ISSUE THREAD

**Issue by tonyxiao** [paulsamuels/SBConstants#24]
SBConstants take a query cli parameter, but I can't seem to find any docs describing what it does.

**Comment by paulsamuels** [comment]
This could certainly do with some documentation.

Basically the flag allows you to provide the path to a `.yml` file that defines what identifiers are looked up when parsing xibs. The default file that is used is [here](https://github.com/paulsamuels/SBConstants/blob/master/lib/sbconstants/identifiers.yml).

To be honest it was probably a premature feature that would allow users to update the queries used during parsing without relying on a new release of the gem - as yet no one has ever raised that they needed more identifiers.

I'll leave this issue open as documentation should be updated

**Comment by paulsamuels** [comment]
Closing as this is now covered in the README. Thanks for the feedback
