### ISSUE TITLE
Raw value missing in generated constant file.

### ISSUE THREAD

**Issue by madnik** [paulsamuels/SBConstants#48]
Generated constant file doesn't contain raw String Value identifiers.

example:

```
public enum TableViewCellReuseIdentifier : String {
    case MessageCell
}
```

**Comment by mkubenka** [comment]
@orta Support for storyboard identifiers with spaces was removed in d935c6dace92ca4cebfd35eccc1e647623f6b0d4

**Comment by madnik** [comment]
Closing: #41 Removed this as this is not necessary.
